services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro
    depends_on:
      - jaeger
    ports:
      - "14317:4317"
      - "14318:4318"
